<?php
    $form = $this->form;
    
    $form->get('title')->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'Title'
        ]);
    $form->get('description')->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'Description'
        ]);
    $form->get('author_id')->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'Author'
        ]);
    $form->get('category_id')->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'Category'
        ]);        

    $form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
    $form->get('submit')->setValue('Save');
    $form->prepare();

?>

<h1>Add Book</h1>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('title')); ?>
            <?= $this->formElement($form->get('title')); ?>
            <?= $this->formElementErrors($form->get('title')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('description')); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('author_id')); ?>
            <?= $this->formElement($form->get('author_id')); ?>
            <?= $this->formElementErrors($form->get('author_id')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('category_id')); ?>
            <?= $this->formElement($form->get('category_id')); ?>
            <?= $this->formElementErrors($form->get('category_id')); ?>
        </div>
        
       
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   