<?php
 
 $title = 'Delete Book';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Are you sure that you want to delete
     '<?php echo $this->escapeHtml($book->getTitle()); ?>'     
 </p>
 
 <?php 
    $url = $this->url('book', ['action' => 'delete', 'id' => $this->id]);
?>

 <form action="<?php echo $url; ?>" method="POST">
 <div>
     <input type="hidden" name="id" value="<?php echo $book->getId(); ?>" />
     <input type="submit" name="delete" value="Yes" type="button" class="btn btn-danger" />
     <input type="submit" name="delete" value="No" type="button" class="btn btn-primary"/>
 </div>
 </form>