<h1 class="text-center mt-4">All Books</h1>

<div class="pull-right">
    <p>
        <a href="<?php echo $this->basePath('book/add');?>">
        <button type="button" class="btn btn-primary">Add New Book</button></a>
    </p>
</div>

<table class="table">
  <thead>
    <tr>      
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Author</th>
      <th scope="col">Category</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    <?php if(count($books) > 0): ?>
      <?php foreach ($books as $book): ?>
        <tr>
          <td><?php echo $book->getTitle(); ?></td>
          <td><?php echo $book->getDescription(); ?></td>
          <td><?php echo $book->getAuthorId(); ?></td>
          <td><?php echo $book->getCategoryId(); ?></td>
          <td><a href="<?php echo $this->url('book', ['action' => 'edit', 'id' => $book->getId() ]); ?>"><button type="button" class="btn btn-primary mb-2">Edit</button></a></td>
          <td><a href="<?php echo $this->url('book', ['action' => 'delete', 'id' => $book->getId() ]); ?>"><button type="button" class="btn btn-danger mb-2">Delete</button></a></td>          
      <?php endforeach; ?>
    <?php else: ?>
      <tr>
        <td>No Records Found!</td>
      </tr>
    <?php endif; ?>
    </tr>    
  </tbody>
</table>
